-- batch_1 建表SQL
-- 自动生成时间: 2025-12-18
-- 数据源: 625试验数据_修改过后.xlsx

CREATE TABLE IF NOT EXISTS exp_data_batch_1 (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID（自增主键）',
    `编号` VARCHAR(255) COMMENT '编号',
    `物性_材料` VARCHAR(255) COMMENT '物性_材料',
    `物性_材料厚度` VARCHAR(255) COMMENT '物性_材料厚度',
    `接头类型` VARCHAR(255) COMMENT '接头类型',
    `光斑尺寸（mm）` VARCHAR(255) COMMENT '光斑尺寸（mm）',
    `视觉系统` VARCHAR(255) COMMENT '视觉系统',
    `电流` VARCHAR(255) COMMENT '电流',
    `正面保护气类型` VARCHAR(255) COMMENT '正面保护气类型',
    `正面保护气流量（L/min）` VARCHAR(255) COMMENT '正面保护气流量（L/min）',
    `背面保护气类型` VARCHAR(255) COMMENT '背面保护气类型',
    `背面保护气流量（L/min）` VARCHAR(255) COMMENT '背面保护气流量（L/min）',
    `工艺_激光功率` VARCHAR(255) COMMENT '工艺_激光功率',
    `工艺_焊接速度` VARCHAR(255) COMMENT '工艺_焊接速度',
    `激光倾角` VARCHAR(255) COMMENT '激光倾角',
    `离焦量` VARCHAR(255) COMMENT '离焦量',
    `送丝速度` VARCHAR(255) COMMENT '送丝速度',
    `焊丝` VARCHAR(255) COMMENT '焊丝',
    `焊丝直径` VARCHAR(255) COMMENT '焊丝直径',
    `焊缝宽度` VARCHAR(255) COMMENT '焊缝宽度',
    `熔深（mm）` VARCHAR(255) COMMENT '熔深（mm）',
    `焊脚高度` VARCHAR(255) COMMENT '焊脚高度',
    `焊缝形貌` VARCHAR(255) COMMENT '焊缝形貌',
    `内部质量` VARCHAR(255) COMMENT '内部质量',
    `尺寸` VARCHAR(255) COMMENT '尺寸',
    `性能_拉伸性能（温度23℃）抗拉强度MPa` VARCHAR(255) COMMENT '性能_拉伸性能（温度23℃）抗拉强度MPa',
    `性能_拉伸性能（温度23℃）断后伸长率%` VARCHAR(255) COMMENT '性能_拉伸性能（温度23℃）断后伸长率%',
    `性能_拉伸性能（温度23℃）屈服强度MPa` VARCHAR(255) COMMENT '性能_拉伸性能（温度23℃）屈服强度MPa',
    `无损照片号` VARCHAR(255) COMMENT '无损照片号',
    `无损结果` VARCHAR(255) COMMENT '无损结果',
    `性能_弯曲性能` VARCHAR(255) COMMENT '性能_弯曲性能',
    `性能_剪切性能` VARCHAR(255) COMMENT '性能_剪切性能',
    `金相组织` VARCHAR(255) COMMENT '金相组织',
    `工艺` VARCHAR(255) COMMENT '工艺',
    `挂靠项目任务号` VARCHAR(255) COMMENT '挂靠项目任务号',
    data_source ENUM('experiment', 'literature') NOT NULL DEFAULT 'experiment' COMMENT '数据来源',
    related_files JSON COMMENT '关联文件列表',
    notes TEXT COMMENT '备注信息',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by VARCHAR(50) COMMENT '创建人',
    updated_by VARCHAR(50) COMMENT '更新人',
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='exp_data_batch_1';
